# Generated by Django 4.1.2 on 2022-10-31 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("brokerage", models.CharField(max_length=20)),
                ("number", models.CharField(max_length=13, unique=True)),
                ("name", models.CharField(max_length=20)),
                ("investment_principal", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.user",
                    ),
                ),
            ],
            options={
                "db_table": "account",
                "abstract": False,
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=20)),
                ("isin_number", models.CharField(max_length=12)),
                ("group", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "stock",
                "abstract": False,
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="InvestInfo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.IntegerField()),
                ("current_price", models.IntegerField()),
                (
                    "account",
                    models.ForeignKey(
                        db_column="account_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="invest.account",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        db_column="stock_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="invest.stock",
                    ),
                ),
            ],
            options={
                "db_table": "invest_info",
                "abstract": False,
                "managed": True,
            },
        ),
    ]
