# Generated by Django 4.1.2 on 2022-11-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invest", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="investinfo",
            name="account_isin_number",
            field=models.CharField(default="", max_length=26, unique=True),
        ),
    ]
